### ISSUE TITLE
Cannot read property 'length' of undefined			

### ISSUE THREAD

**Issue by qpoisson** [gkjohnson/collada-exporter-js#22]
In function processObject,  Line 505

`matids = new Array( o.geometry.groups.length )	`			

causes the following error:

"Uncaught TypeError: Cannot read property 'length' of undefined
    at processObject (ColladaExporter.js:505)
    at THREE.ColladaExporter.parse (ColladaExporter.js:549)"

It looks like that "o" is a Three.Geometry which has no property of "groups". How do you make it work ?

**Comment by gkjohnson** [comment]
Looks like a bug -- the geometry is converted to a `BufferGeometry` in `processGeometry` but that isn't used when looking at the groups.

I'll fix it when I get a chance but in the mean time you could convert the geometry to BufferGeometry manually before exporting to work around the issue.

Thanks for submitting the issue!

**Comment by gkjohnson** [comment]
@qpoisson 

I just merged a fix for this in PR https://github.com/gkjohnson/collada-exporter-js/pull/23 and published a new version to NPM.

Thanks again for letting me know!
