### ISSUE TITLE
Support other sampler textures

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/collada-exporter-js#5]
Only diffuse textures are supported at the moment. Include AO, specular, etc maps

**Comment by sonuhawk** [comment]
Its Coming as 0 size when using your example.html

**Comment by gkjohnson** [comment]
Hey! Thanks for the feedback!

Can I ask for a little more detail? What's 0 size? Unfortunately the example doesn't have any textures yet, so it doesn't show texture export at all. At the moment I would only expect diffuse textures to work. Are you seeing something different?

Thanks!

**Comment by sonuhawk** [comment]
Thank you for Writing back. Its awesome , I made some mistake but its working for me now :) 

var geometry1 = new THREE.DodecahedronGeometry(2,1);
 var material1 = new THREE.MeshLambertMaterial({color:0xFFFFFF, wireframe:true});
 var mesh1 = new THREE.Mesh(geometry1,material1);


var geometry2 = new THREE.SphereBufferGeometry( 2, 2, 2 );
 var material2 = new THREE.MeshPhongMaterial({color:0xFF8FF, wireframe:false});
 var mesh2 = new THREE.Mesh( geometry2, material2 );



 camera.position.z = 3;

 group = new THREE.Object3D();
 group.add( mesh2, mesh1 );
  Scene.add( group );
        
        var obj = new THREE.Object3D();
        var loader = new THREE.ColladaLoader();
        var exp = new THREE.ColladaExporter();

        //obj.add(mesh1);
         //obj.add(mesh2);
         var { data } = exp.parse(group);
        console.log('Format', data);

Am i doing this correct. Please provide your inputs :)

**Comment by gkjohnson** [comment]
Of course!

It looks right to me! Is it all working for you? Admittedly I haven't touched this in awhile but if things aren't working for you I'm happy to take more of a look. Just keep in mind the other limitations listed in the README.

It's great to see someone using this. Can I ask what you're using it for (mesh editor / exporter, conversion scripts, etc)?

**Comment by sonuhawk** [comment]
Hello, 

I am new to Three.JS :)
I have limited knowledge , because i am still learning. 

Yes , I am able to see the Colldada in my console , Its working for me.
I have to try for textures as well. I have not tried it yet.
I am using this to export Mesh data.

Thank you once again :) , Will write to you if i find issues.
